### ISSUE TITLE
Ignore empty lines for radio button layout generation.

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/CSAMS#113]
Form field radio should check for empty lines. Empty lines (erronous based on pressing return after the last entry) should be ignored when generating the radio buttons.

Low
medium
high
<- if this is empty line, it should be ignored

**Comment by kongebra** [comment]
Works now. Removes all empty lines.

**Example:**
Input:
```
Low

Medium



High


Extreamly High

```

Output:
```
Low
Medium
High
Extreamly High
```
