### ISSUE TITLE
Reseting user passwords in "Manage students" menu does not work

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/CSAMS#115]
see title. The activity pretends to reset it and confirms the success. However, the new password doesn't seem to be stored (login not possible).

**Comment by BredeFK** [comment]
This worked fine for me, are you sure you didn't type wrong or something?

**Comment by BredeFK** [comment]
nvm, it didn't work on `eksde.net` I will look further in to this

**Comment by JohanAanesen** [comment]
this has been fixed 015026d02e6853eef8c35a5e3b3ef17008ecae07
