### ISSUE TITLE
Modify default settings for weights for given forms

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/CSAMS#63]
Please adapt the default settings for forms. Submission forms generally don't have weights (in fact, can we make any use of weights in submission forms anyway?), whereas review forms effectively always have weights. The current settings can lead to mistaken activation  of weights when editing assignments.

Just to ensure (I think the system does that already): Forms should keep track as to whether weights had been activated.

**Comment by kongebra** [comment]
What if any future admin-user want to use the submission as a quiz or something like that? Even though they have Blackboard and Insperia from before.

**Comment by chrfrantz** [comment]
Ah ok. Yes, you are right. Thanks for bringing that up! That would imply that we need stats for both submission and review forms, though (if weights are activated, of course).

**Comment by kongebra** [comment]
#77 Implemented this
