### ISSUE TITLE
Display standard deviation in calculated percentage for reviews (both in individual view and summary sheet)

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/CSAMS#86]
Print the standard deviation for reviews in overview for individual student and in generated statistical overview for all reviews. Earmarked for discussion.

**Comment by kongebra** [comment]
@chrfrantz 
Current stage of the statistics
![image](https://user-images.githubusercontent.com/5748207/55400897-62361680-554f-11e9-9c84-84f7c77c8ffd.png)

**Comment by BredeFK** [comment]
Implemented
