### ISSUE TITLE
Use on-demand review assignment instead of fixed assignment of reviews (Grab a review)

### ISSUE THREAD

**Issue by chrfrantz** [JohanAanesen/CSAMS#99]
As discussed; posted here for reference:

Instead of preassigning all reviews to students, why not display the students the number of reviews (not the reviews themselves yet) they have to do and have a "Grab a review" button that students press it when they want to review. Thus, reviews are assigned lazily (random draw amongst least-reviewed submissions) to students and we will always have an open pool of unreviewed (or least-reviewed) submissions. As long as students are signaled how many reviews they have to do, they will grab additional ones (or should - an aspect we can control as discussed below). This enables some opportunities and solves a lot of problems:
1. Students can review more and less reviews than they have to, i.e. committed students can review more and gain additional marks; students that undercommit lose marks. This would allow us to reward prosocial activity in the class. 
2. If too many students commit, we can have additional review rounds, i.e. some submissions may be reviewed three times if students are keen to review --> increase in review quality
3. Latecomers can just be injected into the cycles. Any "Grab a review" request would be drawn from the pool of submissions that had the least reviews, i.e., they would be picked first upon the next request - with the exception of own submissions, of course.
4. We don't have the problem of underreviewing as we have now. Many students may be keen to do additional reviews, but the reviews are associated with students that may not do the reviews (i.e. they are locked) and we will need to deal with that manually.

**Comment by JohanAanesen** [comment]
This has been implemented as of 2cc2e5616e4be38aa61e3bfa5ebc6d8bcc2a3f42
